server:
  port: 8083
  use-forward-headers: true

spring:
  main:
    allow-bean-definition-overriding: true
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    listener:
      acknowledge-mode: client
    template:
      delivery-mode: persistent
      qos-enabled: true
      time-to-live: 10000

management:
  endpoints:
    web:
      exposure:
        include: health, env, configprops, info

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8081/eureka}
    healthcheck:
      enabled: true

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000