version: '3.1'

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    ports:
    - "3306:3306"
    volumes:
    - ./mysql/init-db:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root

  activemq:
    image: rmohr/activemq
    container_name: activemq
    restart: always
    ports:
    - "61616:61616"
    - "8161:8161"
    - "5672:5672"