server:
  port: 8084

spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=true
    username: root
    password: root
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    listener:
      acknowledge-mode: client
    template:
      delivery-mode: persistent
      qos-enabled: true
      time-to-live: 10000

management:
  endpoints:
    web:
      exposure:
        include: health, env, configprops, info

eureka:
  instance:
    hostname: localhost
    preferIpAddress: false
  client:
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8081/eureka}
    healthcheck:
      enabled: true

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000