server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8080/eureka}
    registerWithEureka: false
    fetchRegistry: false
  server:
   waitTimeInMsWhenSyncEmpty: 0
   enableSelfPreservation: false